In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\zas\Downloads\Dataset for Data Analytics - Sheet1.csv")
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

In [4]:
df["CouponCode"].value_counts()

CouponCode
FREESHIP    313
WINTER15    292
SAVE10      286
Name: count, dtype: int64

In [5]:

df.drop(["OrderID","CustomerID","ShippingAddress","TrackingNumber"],axis=1,inplace=True,errors='ignore')

In [6]:
df.head()

,Date,Product,Quantity,UnitPrice,PaymentMethod,OrderStatus,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,2023-01-04,Monitor,5,570.62,Debit Card,Shipped,7,SAVE10,Instagram,2853.10
1,2024-08-23,Phone,2,151.35,Online,Shipped,3,SAVE10,Referral,302.70
2,2024-02-27,Tablet,5,550.68,Credit Card,Cancelled,8,FREESHIP,Email,2753.40
3,2023-10-15,Chair,1,273.19,Debit Card,Returned,5,SAVE10,Facebook,273.19
4,2025-05-08,Printer,4,626.01,Online,Delivered,8,SAVE10,Email,2504.04

In [7]:
df['CouponCode'] = df['CouponCode'].fillna('NoCoupon')

In [8]:
df["CouponCode"].value_counts()

CouponCode
FREESHIP    313
NoCoupon    309
WINTER15    292
SAVE10      286
Name: count, dtype: int64

In [9]:
df['Date'] = pd.to_datetime(df['Date'])

df['Month'] = df['Date'].dt.month
df['DayOfWeek'] = df['Date'].dt.day_name()
df['IsWeekend'] = df['Date'].dt.dayofweek >= 5

In [10]:
df.head()

,Date,Product,Quantity,UnitPrice,PaymentMethod,OrderStatus,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Month,DayOfWeek,IsWeekend
0,2023-01-04,Monitor,5,570.62,Debit Card,Shipped,7,SAVE10,Instagram,2853.10,1,Wednesday,False
1,2024-08-23,Phone,2,151.35,Online,Shipped,3,SAVE10,Referral,302.70,8,Friday,False
2,2024-02-27,Tablet,5,550.68,Credit Card,Cancelled,8,FREESHIP,Email,2753.40,2,Tuesday,False
3,2023-10-15,Chair,1,273.19,Debit Card,Returned,5,SAVE10,Facebook,273.19,10,Sunday,True
4,2025-05-08,Printer,4,626.01,Online,Delivered,8,SAVE10,Email,2504.04,5,Thursday,False

In [11]:
df.shape

(1200, 13)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1200 non-null   datetime64[ns]
 1   Product         1200 non-null   object
 2   Quantity        1200 non-null   int64
 3   UnitPrice       1200 non-null   float64
 4   PaymentMethod   1200 non-null   object
 5   OrderStatus     1200 non-null   object
 6   ItemsInCart     1200 non-null   int64
 7   CouponCode      1200 non-null   object
 8   ReferralSource  1200 non-null   object
 9   TotalPrice      1200 non-null   float64
 10  Month           1200 non-null   int32
 11  DayOfWeek       1200 non-null   object
 12  IsWeekend       1200 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(2), int32(1), int64(2), object(6)
memory usage: 109.1+ KB

In [13]:
df.duplicated().sum()

np.int64(0)

In [31]:
df.to_csv("cleaned_ecommerce_data.csv", index=False)